theme: jekyll-theme-minimal
title: afrodidact's homepage
description: Aaron Nathan Miller, aka The Afrodidact.

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
